# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0006_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.IntegerField()),
                ('coords', models.CharField(max_length=20)),
                ('tagged_user', models.CharField(default='', max_length=20)),
                ('tagged_by', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sign_up_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='baseurl',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
