# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0007_auto_20171101_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototag',
            name='coords',
            field=models.CharField(max_length=40),
        ),
    ]
